# fly.toml app configuration file generated for holdem-demo-backend on 2026-07-23T13:05:35+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "holdem-demo-backend"
primary_region = "nrt"

[build]
  # 같은 폴더에 있는 Dockerfile을 사용해서 빌드하겠다는 의미입니다.
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
