name: Fly Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # backend 폴더 내 코드가 변경되었을 때만 배포 실행

jobs:
  deploy:
    name: Deploy App to Fly.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        working-directory: ./backend # backend 서브폴더 경로 지정
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}